name: "Frontend: style check and deploy"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
    - name: Intalling Node.js dependencies
      run: pnpm install
    - name: Generate index.html
      run: bundle exec rake
    - name: Performing Style Check for Frontend
      run: pnpm lint
    - name: Build
      run: pnpm run build
    - name: Deploy to Cloudflare Workers
      run: pnpx wrangler pages deploy --branch ${{ github.ref == 'refs/heads/main' && 'production' || github.ref_name }} ./dist
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
